migration:
  name: 'vertica-to-postgresql-migration'
  description: 'Migrate data from Vertica to PostgreSQL with schema transformation'

  source:
    type: 'vertica'
    host: '${VERTICA_HOST}'
    port: '${VERTICA_PORT}'
    database: '${VERTICA_DATABASE}'
    username: '${VERTICA_USERNAME}'
    password: '${VERTICA_PASSWORD}'
    ssl: false
    schema_path: 'schemas/source/vertica'
    default_schema: 'DPWTANBEEH'

  target:
    type: 'postgresql'
    host: '${POSTGRES_HOST}'
    port: '${POSTGRES_PORT}'
    database: '${POSTGRES_DATABASE}'
    username: '${POSTGRES_USERNAME}'
    password: '${POSTGRES_PASSWORD}'
    ssl: false
    schema_path: 'schemas/target/postgresql'
    default_schema: 'dpwtanbeeh'

  mappings:
    path: 'schemas/mappings/vertica-to-postgresql'

  settings:
    batch_size: 10000
    parallel_workers: 4
    validation_enabled: true
    rollback_enabled: true
    continue_on_error: false
    max_retries: 3
    retry_delay: 1000
    log_level: 'info'
    progress_reporting: true
